# Generated by Django 6.0 on 2025-12-15 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributers', '0002_distributor_region'),
        ('items_catalogue', '0004_remove_catalogueitem_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_deducted_from', models.CharField(choices=[('SELF', 'Self (Sales Agent)'), ('DISTRIBUTOR', 'Distributor')], default='SELF', help_text='Whether points are deducted from the sales agent or distributor', max_length=20)),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total points for all items in this request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the request', max_length=20)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the request was created')),
                ('date_reviewed', models.DateTimeField(blank=True, help_text='Date and time when the request was reviewed', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks about the request', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection, if applicable', null=True)),
                ('requested_by', models.ForeignKey(help_text='Sales agent who created this request', on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_for', models.ForeignKey(help_text='Distributor for whom the items are being redeemed', on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='distributers.distributor')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who approved or rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redemption Request',
                'verbose_name_plural': 'Redemption Requests',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units requested')),
                ('points_per_item', models.PositiveIntegerField(help_text='Points per item at the time of request (snapshot)')),
                ('total_points', models.PositiveIntegerField(help_text='Total points for this line item (quantity × points_per_item)')),
                ('request', models.ForeignKey(help_text='The redemption request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.redemptionrequest')),
                ('variant', models.ForeignKey(help_text='The catalogue item variant being redeemed', on_delete=django.db.models.deletion.CASCADE, related_name='redemption_items', to='items_catalogue.variant')),
            ],
            options={
                'verbose_name': 'Redemption Request Item',
                'verbose_name_plural': 'Redemption Request Items',
                'ordering': ['id'],
            },
        ),
    ]
