# Generated by Django 6.0 on 2026-01-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('teams', '0002_create_default_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team that this request belongs to (set at creation time)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_requests', to='teams.team'),
        ),
    ]
