# Generated by manual data migration on 2026-01-08

from django.db import migrations


def backfill_team_field(apps, schema_editor):
    """
    Populate the team field for existing redemption requests based on
    the requesting user's current team membership.
    """
    RedemptionRequest = apps.get_model('requests', 'RedemptionRequest')
    TeamMembership = apps.get_model('teams', 'TeamMembership')
    
    # Find all requests with NULL team field
    requests_without_team = RedemptionRequest.objects.filter(team__isnull=True)
    
    updated_count = 0
    skipped_count = 0
    
    for request in requests_without_team:
        # Find the requesting user's team membership
        membership = TeamMembership.objects.filter(user=request.requested_by).first()
        
        if membership:
            # Assign the team from their current membership
            request.team = membership.team
            request.save(update_fields=['team'])
            updated_count += 1
        else:
            # User is not in any team, leave as NULL
            skipped_count += 1
    
    print(f"Backfill complete: {updated_count} requests updated, {skipped_count} skipped (no team membership)")


def reverse_backfill(apps, schema_editor):
    """
    Reversing this migration would set all team fields back to NULL,
    which is destructive. We skip the reverse operation.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_add_team_to_redemption_request'),
        ('teams', '0002_create_default_team'),
    ]

    operations = [
        migrations.RunPython(backfill_team_field, reverse_backfill),
    ]
