# Generated by Django 6.0 on 2026-01-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_backfill_team_for_existing_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the request', max_length=20),
        ),
    ]
