# Generated by Django 6.0 on 2026-01-12 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_add_processed_cancelled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Superadmin who cancelled this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, help_text='Date and time when the request was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='date_processed',
            field=models.DateTimeField(blank=True, help_text='Date and time when the request was marked as processed', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Superadmin who marked this request as processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='processing_status',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='NOT_PROCESSED', help_text='Current processing status of the request (Superadmin level)', max_length=20),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, help_text='Date and time when the request was reviewed by approver', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Approver who approved or rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current approval status of the request (Approver level)', max_length=20),
        ),
    ]
