# Generated by Django 6.0 on 2026-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_separate_approval_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='svc_date',
            field=models.DateField(blank=True, help_text='Service vehicle use date', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='svc_driver',
            field=models.CharField(blank=True, choices=[('WITH_DRIVER', 'With Driver'), ('WITHOUT_DRIVER', 'Without Driver')], help_text='Whether the service vehicle includes a driver', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='svc_time',
            field=models.TimeField(blank=True, help_text='Service vehicle use time', null=True),
        ),
    ]
