# Generated by Django 6.0 on 2026-01-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_redemptionrequest_svc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='withdrawal_reason',
            field=models.TextField(blank=True, help_text='Reason for withdrawal by sales agent, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', help_text='Current approval status of the request (Approver level)', max_length=20),
        ),
    ]
