# Generated by Django 6.0 on 2026-01-16 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_redemptionrequest_withdrawal_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='marketing_approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of marketing approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='marketing_approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Marketing approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='marketing_approved_by',
            field=models.ForeignKey(blank=True, help_text='Marketing user who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='marketing_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for marketing approval rejection', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='requires_marketing_approval',
            field=models.BooleanField(default=False, help_text='Whether this request requires marketing approval'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='requires_sales_approval',
            field=models.BooleanField(default=True, help_text='Whether this request requires sales approver approval'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='sales_approval_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of sales approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='sales_approval_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Sales approver approval status', max_length=20),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='sales_approved_by',
            field=models.ForeignKey(blank=True, help_text='Sales approver who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='sales_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for sales approval rejection', null=True),
        ),
    ]
