# Generated by Django 6.0 on 2026-01-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_redemptionrequest_marketing_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='dynamic_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User-provided value for dynamic calculation (e.g., sq ft, invoice amount, days)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='points_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of points multiplier at request time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='pricing_type',
            field=models.CharField(blank=True, help_text='Pricing type snapshot (FIXED, PER_SQFT, PER_INVOICE, PER_DAY, PER_EU_SRP)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='points_per_item',
            field=models.PositiveIntegerField(blank=True, help_text='Points per item at the time of request (snapshot, for FIXED pricing)', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units requested (for FIXED pricing items)'),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='total_points',
            field=models.PositiveIntegerField(help_text='Total points for this line item'),
        ),
    ]
