# Generated by Django 6.0 on 2026-01-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_redemptionrequestitem_dynamic_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='item_processed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this item was processed by Marketing', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='item_processed_by',
            field=models.ForeignKey(blank=True, help_text='Marketing user who processed this specific item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_request_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
