# Generated by Django 6.0 on 2026-01-21 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_archived_by_customer_date_archived_and_more'),
        ('distributers', '0007_distributor_archived_by_distributor_date_archived_and_more'),
        ('requests', '0010_redemptionrequestitem_item_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='requested_for_customer',
            field=models.ForeignKey(blank=True, help_text='Customer for whom the items are being redeemed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='requested_for_type',
            field=models.CharField(choices=[('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer')], default='DISTRIBUTOR', help_text='Type of entity this request is for (Distributor or Customer)', max_length=20),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='points_deducted_from',
            field=models.CharField(choices=[('SELF', 'Self (Sales Agent)'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer')], default='SELF', help_text='Whether points are deducted from the sales agent or distributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='requested_for',
            field=models.ForeignKey(blank=True, help_text='Distributor for whom the items are being redeemed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to='distributers.distributor'),
        ),
    ]
