# Generated by Django 6.0 on 2026-01-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_redemptionrequest_requested_for_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Name of the driver for service delivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Vehicle plate number for service delivery', max_length=20, null=True),
        ),
    ]
