# Generated by Django 6.0 on 2026-01-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0013_switch_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptionrequest',
            name='marketing_approval_date',
        ),
        migrations.RemoveField(
            model_name='redemptionrequest',
            name='marketing_approval_status',
        ),
        migrations.RemoveField(
            model_name='redemptionrequest',
            name='marketing_approved_by',
        ),
        migrations.RemoveField(
            model_name='redemptionrequest',
            name='marketing_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='redemptionrequest',
            name='requires_marketing_approval',
        ),
    ]
