# Generated by Django 6.0 on 2026-02-12 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0020_product_image'),
        ('requests', '0014_remove_redemptionrequest_marketing_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='product',
            field=models.ForeignKey(help_text='The product being redeemed', on_delete=django.db.models.deletion.PROTECT, related_name='redemption_items', to='items_catalogue.product'),
        ),
    ]
