# Generated by Django 6.0 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_migrate_customer_deduction_to_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequest',
            name='points_deducted_from',
            field=models.CharField(choices=[('SELF', 'Self (Sales Agent)'), ('DISTRIBUTOR', 'Distributor')], default='SELF', help_text='Whether points are deducted from the sales agent or distributor', max_length=20),
        ),
    ]
