# Generated by Django 6.0 on 2026-03-05 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0017_alter_redemptionrequest_points_deducted_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='acknowledgement_receipt',
            field=models.ImageField(blank=True, help_text='Photo of the acknowledgement receipt (max 5MB, PNG/JPG/WebP)', null=True, upload_to='acknowledgement_receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='ar_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('UPLOADED', 'Uploaded')], default='NOT_REQUIRED', help_text='Status of acknowledgement receipt upload (only for customer requests)', max_length=20),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='ar_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the acknowledgement receipt was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='ar_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Sales agent who uploaded the acknowledgement receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_uploaded_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
