# Generated by Django 6.0 on 2026-03-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_redemptionrequest_acknowledgement_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative units fulfilled across all processing passes (for FIXED pricing items)'),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='processing_status',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PARTIALLY_PROCESSED', 'Partially Processed'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='NOT_PROCESSED', help_text='Current processing status of the request (Superadmin level)', max_length=20),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='item_processed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this item was fully processed', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='item_processed_by',
            field=models.ForeignKey(blank=True, help_text='Marketing user who fully processed this specific item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_request_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemFulfillmentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0, help_text='Units fulfilled in this pass (for FIXED pricing; 0 for non-FIXED full-process)')),
                ('fulfilled_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of this fulfillment pass')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this fulfillment pass', null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, help_text='User who performed this fulfillment pass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_fulfillment_logs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The request item this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_logs', to='requests.redemptionrequestitem')),
            ],
            options={
                'verbose_name': 'Item Fulfillment Log',
                'verbose_name_plural': 'Item Fulfillment Logs',
                'ordering': ['fulfilled_at'],
            },
        ),
    ]
