# Generated by Django 6.0 on 2026-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequest',
            name='requested_for_type',
            field=models.CharField(choices=[('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer'), ('SELF', 'Self')], default='DISTRIBUTOR', help_text='Type of entity this request is for (Distributor or Customer)', max_length=20),
        ),
    ]
