# Generated by Django 6.0 on 2026-03-12 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0021_alter_redemptionrequest_requested_for_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(help_text='Photo proof of item handover (max 5MB, PNG/JPG/WebP)', upload_to='processing_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this photo was uploaded')),
                ('caption', models.TextField(blank=True, help_text='Optional caption or note for this photo', null=True)),
                ('request', models.ForeignKey(help_text='The redemption request this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='processing_photos', to='requests.redemptionrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Photo',
                'verbose_name_plural': 'Processing Photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
