# Generated by Django 6.0 on 2026-03-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_processingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='received_by_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the items were received', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='received_by_name',
            field=models.CharField(blank=True, help_text='Printed name of the person who received the items', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='received_by_signature',
            field=models.ImageField(blank=True, help_text='Digital or photo signature of the customer (received by field)', null=True, upload_to='signatures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='received_by_signature_method',
            field=models.CharField(blank=True, choices=[('DRAWN', 'Digital Signature Pad'), ('PHOTO', 'Photo Upload')], help_text='Method used to capture the signature', max_length=10, null=True),
        ),
    ]
