# Generated by Django 6.0 on 2026-03-17 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0023_redemptionrequest_received_by_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptionrequest',
            name='acknowledgement_receipt',
            field=models.FileField(blank=True, help_text='Photo or PDF of the acknowledgement receipt (max 5MB)', null=True, upload_to='acknowledgement_receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='item_processed_by',
            field=models.ForeignKey(blank=True, help_text='Handler user who fully processed this specific item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_request_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
