# Generated by Django 6.0 on 2026-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0024_alter_redemptionrequest_acknowledgement_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Snapshot of extra field values provided at request time', null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequestitem',
            name='pricing_formula',
            field=models.CharField(blank=True, help_text='Snapshot of formula slug used for pricing at request time', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='driver_name',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Name of the driver for service delivery', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='plate_number',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Vehicle plate number for service delivery', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='svc_date',
            field=models.DateField(blank=True, help_text='[DEPRECATED] Service vehicle use date', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='svc_driver',
            field=models.CharField(blank=True, choices=[('WITH_DRIVER', 'With Driver'), ('WITHOUT_DRIVER', 'Without Driver')], help_text='[DEPRECATED] Whether the service vehicle includes a driver', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequest',
            name='svc_time',
            field=models.TimeField(blank=True, help_text='[DEPRECATED] Service vehicle use time', null=True),
        ),
    ]
