# Generated by Django 6.0 on 2026-03-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0025_redemptionrequestitem_extra_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptionrequestitem',
            name='dynamic_quantity',
        ),
        migrations.RemoveField(
            model_name='redemptionrequestitem',
            name='pricing_type',
        ),
        migrations.AlterField(
            model_name='itemfulfillmentlog',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units fulfilled in this pass'),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='fulfilled_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative units fulfilled across all processing passes'),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='points_per_item',
            field=models.PositiveIntegerField(blank=True, help_text='Points per item at the time of request (snapshot)', null=True),
        ),
        migrations.AlterField(
            model_name='redemptionrequestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units requested'),
        ),
    ]
