# Generated by Django 6.0 on 2026-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0026_remove_redemptionrequestitem_dynamic_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='ar_number',
            field=models.CharField(blank=True, help_text='Auto-generated AR number (PRS-XXXX)', max_length=20, null=True, unique=True),
        ),
    ]
