# Generated by Django 6.0 on 2026-04-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_redemptionrequest_ar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='marketing_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for marketing approval rejection (dual-approval marketing track)', null=True),
        ),
    ]
