# Generated by Django 6.0 on 2025-12-10 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options_userprofile_ban_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(blank=True, help_text="Reward category, if applicable (e.g., 'SIGNAGE')", max_length=255, null=True)),
                ('item_name', models.CharField(help_text="Name of the item (e.g., 'PLATINUM SHIRT')", max_length=255)),
                ('item_code', models.TextField(help_text="Item code(s), can be multiple separated by commas (e.g., '[ MC0001 ]' or '[01345, 01346, 01347, 01348]')")),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('purpose', models.TextField(help_text='Purpose of the item')),
                ('specifications', models.TextField(help_text='Specifications of the item')),
                ('options', models.TextField(blank=True, help_text='Available options (e.g., sizes, colors, variants)', null=True)),
                ('points', models.CharField(help_text="Points required (can be numeric or formula like '1/inv amt')", max_length=100)),
                ('price', models.CharField(help_text="Price (e.g., '₱130.00' or 'P0.50/inv amt.')", max_length=100)),
                ('legend', models.CharField(choices=[('COLLATERAL', 'Collateral'), ('GIVEAWAY', 'Giveaway'), ('ASSET', 'Asset'), ('BENEFIT', 'Benefit')], default='GIVEAWAY', help_text='Category legend: Collateral (red), Giveaway (blue), Asset (yellow), Benefit (green)', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date the item was added to the catalogue')),
            ],
            options={
                'verbose_name': 'Catalogue Item',
                'verbose_name_plural': 'Catalogue Items',
                'ordering': ['date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
