# Generated by Django 6.0 on 2025-12-10 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the item was added to the catalogue'),
        ),
    ]
