# Generated by Django 6.0 on 2025-12-13 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0002_catalogueitem_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this catalogue item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this catalogue item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='date_archived',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the item was archived', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the item image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the item is archived'),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
