# Generated by Django 6.0 on 2025-12-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0003_catalogueitem_added_by_catalogueitem_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='catalogueitem',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='catalogueitem',
            name='options',
        ),
        migrations.RemoveField(
            model_name='catalogueitem',
            name='points',
        ),
        migrations.RemoveField(
            model_name='catalogueitem',
            name='price',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text="Unique code for this variant (e.g., '01345')", max_length=50, unique=True)),
                ('option_description', models.CharField(blank=True, help_text="Description of the variant (e.g., 'S', 'Blue S')", max_length=100, null=True)),
                ('points', models.CharField(help_text="Points required (can be numeric or formula like '1/inv amt')", max_length=100)),
                ('price', models.CharField(help_text="Price (e.g., '₱130.00' or 'P0.50/inv amt.')", max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL to the variant image', max_length=500, null=True)),
                ('catalogue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items_catalogue.catalogueitem')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'ordering': ['item_code'],
                'unique_together': {('catalogue_item', 'item_code')},
            },
        ),
    ]
