# Generated by Django 6.0 on 2026-01-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0004_remove_catalogueitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Stock level at which to trigger low stock alert'),
        ),
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Current stock quantity available'),
        ),
    ]
