# Generated by Django 6.0 on 2026-01-13 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0005_variant_reorder_level_variant_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Approver assigned to this catalogue item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='mktg_admin',
            field=models.ForeignKey(blank=True, help_text='Marketing admin assigned to this catalogue item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mktg_admin_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
