# Generated by Django 6.0 on 2026-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0006_catalogueitem_approver_catalogueitem_mktg_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='needs_driver',
            field=models.BooleanField(default=False, help_text='Whether this item requires a driver'),
        ),
    ]
