# Generated by Django 6.0 on 2026-01-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0007_catalogueitem_needs_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='approval_type',
            field=models.CharField(choices=[('SALES', 'Sales Approver Only'), ('MARKETING', 'Marketing Only'), ('BOTH', 'Both Sales & Marketing')], default='SALES', help_text='Who needs to approve requests for this item: Sales Approver, Marketing, or Both', max_length=20),
        ),
    ]
