# Generated by Django 6.0 on 2026-01-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0008_catalogueitem_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='points_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplier for dynamic pricing (e.g., 25 for "25/sq ft" means 25 points per sq ft)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price multiplier for dynamic pricing (e.g., 25.00 for "25.00/sq ft")', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed (standard quantity-based)'), ('PER_SQFT', 'Per Square Foot'), ('PER_INVOICE', 'Per Invoice Amount'), ('PER_DAY', 'Per Day'), ('PER_EU_SRP', 'Per EU SRP')], default='FIXED', help_text='Type of pricing calculation: Fixed, Per Sq Ft, Per Invoice Amount, etc.', max_length=20),
        ),
    ]
