# Generated by Django 6.0 on 2026-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0009_variant_points_multiplier_variant_price_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueitem',
            name='approver',
        ),
    ]
