# Generated by Django 6.0 on 2026-01-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0010_remove_approver_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='committed_stock',
            field=models.IntegerField(default=0, help_text='Stock reserved for pending/approved but unprocessed requests'),
        ),
    ]
