# Generated by Django 6.0 on 2026-01-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0012_flatten_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item_name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
