# Generated by Django 6.0 on 2026-01-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0013_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='catalogue_item',
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='approval_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_target',
        ),
        migrations.DeleteModel(
            name='CatalogueItem',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
