# Generated by Django 6.0 on 2026-01-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0014_remove_variant_catalogue_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mktg_admin',
            field=models.ForeignKey(blank=True, help_text='Marketing admin assigned to process this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mktg_admin_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
