# Generated by Django 6.0 on 2026-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0015_add_mktg_admin_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=True, help_text='Whether this item tracks inventory. False for made-to-order items.'),
        ),
    ]
