# Generated by Django 6.0 on 2026-01-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0016_add_has_stock_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity per order. Null means unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity per order. Default is 1.'),
        ),
    ]
