# Generated by Django 6.0 on 2026-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0017_product_max_order_qty_product_min_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_sales_approval',
            field=models.BooleanField(default=True, help_text='Whether requests containing this product require sales approver approval. If False, skips directly to marketing processing.'),
        ),
    ]
