# Generated by Django 6.0 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0018_product_requires_sales_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='legend',
            field=models.CharField(choices=[('GIVEAWAY', 'Giveaway'), ('MERCH', 'Merch'), ('PROMO', 'Promo'), ('AD_MATERIALS', 'Ad Materials'), ('POINT_OF_SALE', 'Point of Sale'), ('ASSET', 'Asset'), ('OTHERS', 'Others')], default='GIVEAWAY', max_length=20),
        ),
    ]
