# Generated by Django 6.0 on 2026-02-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0019_alter_product_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (max 5MB, PNG/JPG/WebP)', null=True, upload_to='catalogue_images/%Y/%m/'),
        ),
    ]
