# Generated by Django 6.0 on 2026-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0020_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='legend',
            field=models.CharField(choices=[('GIVEAWAY', 'Giveaway'), ('MERCH', 'Merch'), ('PROMO', 'Promo'), ('AD_MATERIALS', 'Ad Materials'), ('POINT_OF_SALE', 'Point of Sale'), ('ASSET', 'Asset'), ('COLLATERAL', 'Collateral'), ('BENEFIT', 'Benefit'), ('OTHERS', 'Others')], default='GIVEAWAY', max_length=20),
        ),
    ]
