# Generated by Django 6.0 on 2026-02-27 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0021_alter_product_legend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Denormalized name for display', max_length=255)),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('stock_delta', models.IntegerField(help_text='new_stock - previous_stock')),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Add Stock'), ('DECREASE', 'Decrease Stock'), ('BULK_ADD', 'Bulk Add'), ('BULK_DECREASE', 'Bulk Decrease'), ('BULK_RESET', 'Bulk Reset')], max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Required for stock decreases')),
                ('batch_id', models.UUIDField(blank=True, help_text='Groups records from a single bulk/batch API call', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_audit_logs', to='items_catalogue.product')),
            ],
            options={
                'verbose_name': 'Stock Audit Log',
                'verbose_name_plural': 'Stock Audit Logs',
                'db_table': 'stock_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='idx_stock_product'), models.Index(fields=['created_at'], name='idx_stock_created_at'), models.Index(fields=['batch_id'], name='idx_stock_batch_id'), models.Index(fields=['changed_by'], name='idx_stock_changed_by')],
            },
        ),
    ]
