# Generated by Django 6.0 on 2026-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0023_trim_legend_to_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate for dynamic pricing (e.g. 25 for "25 pts per sq ft"). Unused for FIXED pricing.', max_digits=10, null=True),
        ),
    ]
