# Generated by Django 6.0 on 2026-03-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0024_add_points_multiplier_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_formula',
            field=models.CharField(choices=[('NONE', 'None (use standard pricing)'), ('DRIVER_MULTIPLIER', 'Driver Multiplier (2x if with driver)'), ('AREA_RATE', 'Area Rate (L × W × H × rate)')], default='NONE', help_text='Pre-built formula for computing points from extra field inputs', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('CHOICE', 'Choice (Dropdown)')], max_length=10)),
                ('choices_json', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='items_catalogue.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
