# Generated by Django 6.0 on 2026-03-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0025_product_pricing_formula_productextrafield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricing_type',
        ),
    ]
