# Generated by Django 6.0 on 2026-03-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_catalogue', '0026_remove_product_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricing_formula',
            field=models.CharField(choices=[('NONE', 'None (use standard pricing)'), ('PER_SQFT', 'Per Square Foot (sqft × multiplier)'), ('PER_INVOICE', 'Per Invoice (amount × multiplier)'), ('PER_DAY', 'Per Day (days × multiplier)'), ('DRIVER_MULTIPLIER', 'Driver Multiplier (2x if with driver)'), ('AREA_RATE', 'Area Rate (L × W × H × rate)')], default='NONE', help_text='Pre-built formula for computing points from extra field inputs', max_length=30),
        ),
    ]
