# Generated by Django 6.0 on 2025-12-29 02:24

from django.db import migrations


def create_default_team(apps, schema_editor):
    """Create a default team and assign existing Sales Agents and Distributors to it"""
    Team = apps.get_model('teams', 'Team')
    TeamMembership = apps.get_model('teams', 'TeamMembership')
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    Distributor = apps.get_model('distributers', 'Distributor')
    
    # Find first approver
    approver_profile = UserProfile.objects.filter(position='Approver').first()
    approver = approver_profile.user if approver_profile else None
    
    # Create default team
    default_team = Team.objects.create(
        name='Default Team',
        approver=approver,
        region='Unassigned'
    )
    
    print(f"✓ Created default team: {default_team.name}")
    
    # Assign all Sales Agents to default team
    sales_agent_profiles = UserProfile.objects.filter(position='Sales Agent')
    member_count = 0
    for sa_profile in sales_agent_profiles:
        TeamMembership.objects.create(
            team=default_team,
            user=sa_profile.user
        )
        member_count += 1
    
    print(f"✓ Assigned {member_count} Sales Agents to {default_team.name}")
    
    # Assign all distributors without team to default team
    distributor_count = Distributor.objects.filter(team__isnull=True).update(team=default_team)
    
    print(f"✓ Assigned {distributor_count} distributors to {default_team.name}")


def reverse_default_team(apps, schema_editor):
    """Remove the default team"""
    Team = apps.get_model('teams', 'Team')
    
    try:
        default_team = Team.objects.get(name='Default Team')
        default_team.delete()
        print("✓ Removed default team")
    except Team.DoesNotExist:
        print("! Default team does not exist")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('distributers', '0004_distributor_team'),
        ('users', '0007_alter_userprofile_position'),  # Adjust if needed
    ]

    operations = [
        migrations.RunPython(create_default_team, reverse_code=reverse_default_team),
    ]
