# Generated by Django 6.0 on 2026-01-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_create_default_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
    ]
