# Generated by Django 6.0 on 2026-01-12 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='marketing_admin',
            field=models.ForeignKey(blank=True, help_text='Marketing admin assigned to this team', limit_choices_to={'profile__position': 'Marketing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
