# Generated by Django 6.0 on 2026-01-13 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_marketing_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='date_archived',
            field=models.DateTimeField(blank=True, help_text='Date and time when the team was archived', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this team is archived'),
        ),
    ]
