# Generated by Django 6.0 on 2026-01-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_archived_by_team_date_archived_team_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='marketing_admin',
        ),
    ]
