# Generated by Django 6.0 on 2026-02-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_marketing_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='approver',
        ),
    ]
