# Generated by Django 6.0 on 2026-03-10 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_teammembership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Approver who manages this team', limit_choices_to={'profile__position__in': ['Approver', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
