# Generated by Django 6.0 on 2026-02-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('USER', 'User Account'), ('DISTRIBUTOR', 'Distributor'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('entity_id', models.IntegerField(help_text='Primary key of the affected entity')),
                ('entity_name', models.CharField(help_text='Denormalized name for display', max_length=255)),
                ('previous_points', models.IntegerField()),
                ('new_points', models.IntegerField()),
                ('points_delta', models.IntegerField(help_text='new_points - previous_points')),
                ('action_type', models.CharField(choices=[('INDIVIDUAL_SET', 'Individual Set'), ('BULK_DELTA', 'Bulk Delta'), ('BULK_RESET', 'Bulk Reset')], max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason/note for the change')),
                ('batch_id', models.UUIDField(blank=True, help_text='Groups records from a single bulk/batch API call', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The superadmin who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Audit Log',
                'verbose_name_plural': 'Points Audit Logs',
                'db_table': 'points_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_entity'), models.Index(fields=['created_at'], name='idx_created_at'), models.Index(fields=['batch_id'], name='idx_batch_id'), models.Index(fields=['changed_by'], name='idx_changed_by')],
            },
        ),
    ]
