# Generated by Django 6.0 on 2026-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_audit', '0002_alter_pointsauditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsauditlog',
            name='action_type',
            field=models.CharField(choices=[('INDIVIDUAL_SET', 'Individual Set'), ('BULK_DELTA', 'Bulk Delta'), ('BULK_RESET', 'Bulk Reset'), ('REDEMPTION_DEDUCT', 'Redemption Deduction'), ('REDEMPTION_REFUND', 'Redemption Refund'), ('SALES_VOL_ALLOC', 'Sales Volume Allocation')], max_length=20),
        ),
    ]
