# Generated by Django 6.0 on 2026-01-12 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('location', models.CharField(help_text='Location of the customer', max_length=255)),
                ('points', models.PositiveIntegerField(default=0, help_text='Current points balance for the customer')),
                ('date_added', models.DateField(auto_now_add=True, help_text='Date the customer was added')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
