# Generated by Django 6.0 on 2026-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_archived_by_customer_date_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0, help_text='Current points balance for the customer (can be negative)'),
        ),
    ]
