# Generated by Django 6.0 on 2026-02-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand associated with the customer', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_channel',
            field=models.CharField(blank=True, default='', help_text='Sales channel for the customer', max_length=255),
        ),
    ]
