# Generated by Django 6.0 on 2026-03-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
    ]
