# Generated by Django 6.0 on 2025-12-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_catalogueitem_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogueItem',
        ),
    ]
