# Generated by Django 6.0 on 2025-12-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_catalogueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Current points balance for the user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uses_points',
            field=models.BooleanField(default=False, help_text='Whether this user uses the points system'),
        ),
    ]
