# Generated by Django 6.0 on 2025-12-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_points_userprofile_uses_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Sales Agent', 'Sales Agent'), ('Approver', 'Approver'), ('Marketing', 'Marketing'), ('Reception', 'Reception'), ('Executive Assistant', 'Executive Assistant')], max_length=100),
        ),
    ]
