# Generated by Django 6.0 on 2026-01-13 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this user profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_archived',
            field=models.DateTimeField(blank=True, help_text='Date and time when the user profile was archived', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this user profile is archived'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales Agent', 'Sales Agent'), ('Approver', 'Approver'), ('Marketing', 'Marketing'), ('Reception', 'Reception'), ('Executive Assistant', 'Executive Assistant')], max_length=100),
        ),
    ]
