# Generated by Django 6.0 on 2026-01-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_archived_by_userprofile_date_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, help_text='Current points balance for the user (can be negative)'),
        ),
    ]
