# Generated by Django 6.0 on 2026-02-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_message',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unban_date',
        ),
    ]
