# Generated by Django 6.0 on 2026-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales Agent', 'Sales Agent'), ('Approver', 'Approver'), ('Marketing', 'Marketing')], max_length=100),
        ),
    ]
