# Generated by Django 6.0 on 2026-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_self_request',
            field=models.BooleanField(default=False, help_text='Whether this approver can create redemption requests for themselves'),
        ),
    ]
