# Generated by Django 6.0 on 2026-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_marketing_to_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether this user wants to receive email notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Sales Agent', 'Sales Agent'), ('Approver', 'Approver'), ('Handler', 'Handler')], max_length=100),
        ),
    ]
