# Generated by Django 6.0 on 2025-12-15 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the distributor', max_length=255)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('location', models.CharField(help_text='Location of the distributor', max_length=255)),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date the distributor was added')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this distributor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_distributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['name'],
            },
        ),
    ]
