# Generated by Django 6.0 on 2025-12-15 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, help_text='Region where the distributor operates', max_length=100),
            preserve_default=False,
        ),
    ]
