# Generated by Django 6.0 on 2025-12-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0002_distributor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Current points balance for the distributor'),
        ),
    ]
