# Generated by Django 6.0 on 2025-12-29 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0003_distributor_points'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team that this distributor is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='teams.team'),
        ),
    ]
