# Generated by Django 6.0 on 2026-01-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0004_distributor_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='team',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='date_added',
            field=models.DateField(auto_now_add=True, help_text='Date the distributor was added'),
        ),
    ]
