# Generated by Django 6.0 on 2026-01-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0005_remove_distributor_team_alter_distributor_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='region',
        ),
    ]
