# Generated by Django 6.0 on 2026-01-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0007_distributor_archived_by_distributor_date_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='points',
            field=models.IntegerField(default=0, help_text='Current points balance for the distributor (can be negative)'),
        ),
    ]
