# Generated by Django 6.0 on 2026-03-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0008_alter_distributor_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='phone',
        ),
        migrations.AddField(
            model_name='distributor',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Brand associated with the distributor', max_length=255),
        ),
        migrations.AddField(
            model_name='distributor',
            name='sales_channel',
            field=models.CharField(blank=True, default='', help_text='Sales channel for the distributor', max_length=255),
        ),
    ]
