# Generated by Django 6.0 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0009_remove_distributor_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='points',
            field=models.IntegerField(default=0, help_text='Current points balance for the distributor (minimum 0)'),
        ),
    ]
